name: ci

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
    - name: Run tests run-time tokio
      run: cargo test --features=runtime-tokio
    - name: Run test runtime async-std
      run: cargo test --features=runtime-async-std
